### ISSUE TITLE
Where is ShufflePatches?

### ISSUE THREAD

**Issue by roomo7time** [SongweiGe/Contrastive-Learning-with-Non-Semantic-Negatives#1]
https://github.com/SongweiGe/Contrastive-Learning-with-Non-Semantic-Negatives/blob/5fbdc4d84346afa7a17ae2632cab38a6291d69fb/moco/loader.py#L217

Sorry, but I cannot find `ShufflePatches` in the code.

**Comment by songweige** [comment]
Thank you for pointing that out. ShufflePatches was the initial version of the patch-based transformation, which simply permutes all the patches in the images. In practice, we found that ShufflePatches underperforms the patch-based method. Therefore we didn't proceed with it. Please feel free to ignore it.
